services:
  frontend: &frontend
    container_name: ip-frontend
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
      target: ip_frontend_prod
    environment:
      - NODE_ENV=development
      #if you’re using Windows, you may need to uncomment the next line - Sol from @Kobe E
      #- WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  frontend-dev:
    <<: *frontend
    container_name: ip_frontend_dev
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
      target: ip_frontend_dev
    restart: always
    command: yarn dev
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend.dkr:8000
      - REDIS_URL=redis://redis.dkr:6379
    env_file:
      - path: frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      ip_network:
        aliases:
          - frontend.dkr

  frontend-test:
    <<: *frontend
    container_name: ip_frontend_test
    command: yarn test
    environment:
      - NODE_ENV=development

  backend: &backend
    image: "ip_backend"
    container_name: ip_backend
    build:
      context: .
      dockerfile: docker/backend.dockerfile
      target: ip_backend

    ports:
      - "8000:8000"

  backend-dev:
    <<: *backend
    container_name: ip_backend_dev
    build:
      context: .
      dockerfile: docker/backend.dockerfile
      target: ip_dev
    environment:
      - ALLOWED_HOSTS=localhost,backend.dkr
      - STATIC_URL=/static/
      - MEDIA_URL=/media/
      - REDIS_URL=redis://redis.dkr:6379
      - CSRF_TRUSTED_ORIGINS=http://localhost:4000
    env_file:
      - path: backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/src
    networks:
      ip_network:
        aliases:
          - backend.dkr

  backend-test:
    <<: *backend
    container_name: ip-backend-test
    command: python manage.py test
    build:
      context: .
      dockerfile: docker/backend.dockerfile
      target: ip_test
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/src

  proxy-dev:
    container_name: ip_proxy_dev
    build:
      context: .
      dockerfile: docker/proxy.dockerfile
      target: ip_proxy_dev
    ports:
      - "4000:80"
    depends_on:
      - frontend-dev
      - backend-dev
    networks:
      ip_network:
        aliases:
          - proxy.dkr

  redis-dev:
    container_name: ip_redis_dev
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      ip_network:
        aliases:
          - redis.dkr

networks:
  ip_network:
    name: ip_network