version: "3.8"
services:
  frontend: &frontend
    container_name: ip-frontend
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
      target: ip_frontend_prod
    environment:
      - NODE_ENV=development
      #if you’re using Windows, you may need to uncomment the next line - Sol from @Kobe E
      #- WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  frontend-dev:
    <<: *frontend
    container_name: ip_frontend_dev
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
      target: ip_frontend_dev
    restart: always
    command: yarn dev
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend.dkr:8000
      #if you’re using Windows, you may need to uncomment the next line - Sol from @Kobe E
      #- WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - ip_network

  frontend-test:
    <<: *frontend
    container_name: ip_frontend_test
    command: yarn test
    environment:
      - NODE_ENV=development

  backend: &backend
    image: "ip_backend"
    container_name: ip_backend
    build:
      context: .
      dockerfile: docker/backend.dockerfile
      target: ip_backend

    ports:
      - "8000:8000"

  backend-dev:
    <<: *backend
    container_name: ip_backend_dev
    build:
      context: .
      dockerfile: docker/backend.dockerfile
      target: ip_dev
    environment:
      - ALLOWED_HOSTS=localhost,backend.dkr
      - DEFAULT_DATABASE_URL=sqlite:////src/db.sqlite3
      - DEBUG=on
      - STATIC_URL=/static/
      - MEDIA_URL=/media/
      - SECRET_KEY=django-insecure-)c%s=kj@d9l-n9uv!p&8&60=k74n(y4mf3g*c5r+)5ode7p%k8
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/src
    networks:
      ip_network:
        aliases:
          - backend.dkr

  backend-test:
    <<: *backend
    container_name: ip-backend-test
    command: python manage.py test
    build:
      context: .
      dockerfile: docker/backend.dockerfile
      target: ip_test
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/src

networks:
  ip_network:
    name: ip_network