# Generated by Django 5.1.5 on 2025-03-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletecreatedbypermission',
            options={'default_permissions': (), 'managed': False, 'permissions': (('delete_own_created_by_instances', 'Can delete own created by instances'), ('change_own_created_by_instances', 'Can change own created by instances'))},
        ),
    ]
