# Generated by Django 5.1.5 on 2025-03-05 09:14

import file.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedfile',
            name='filename',
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='file',
            field=models.FileField(upload_to=file.models.RelatedFile.get_file_path),
        ),
    ]
