# Generated by Django 5.1.5 on 2025-03-02 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thingy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('media_thing', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thingy', to='file.file')),
            ],
        ),
    ]
