# Generated by Django 5.1.5 on 2025-03-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_thingy'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='namespace',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
