# Generated by Django 5.1.5 on 2025-02-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_businessarea_name_alter_businessarea_slug'),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='business_areas',
            field=models.ManyToManyField(blank=True, to='business.businessarea'),
        ),
        migrations.AlterField(
            model_name='campaignround',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
