# Generated by Django 5.1.5 on 2025-02-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='random_token',
            field=models.CharField(default='dcd3660246d5428291869e89ea04263b', max_length=32, unique=True),
        ),
    ]
