# Generated by Django 5.1.5 on 2025-02-17 11:27

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_random_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='random_token',
            field=models.CharField(default="abc123", max_length=32, unique=True),
        ),
    ]
