# Generated by Django 5.1.5 on 2025-02-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profiletoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='random_token',
        ),
    ]
