# Generated by Django 5.1.5 on 2025-02-17 18:37

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_random_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletoken',
            name='expires_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
