# Generated by Django 5.1.5 on 2025-02-20 13:59

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profiletoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletoken',
            name='token',
            field=models.CharField(db_index=True, default="abc123", max_length=32, unique=True),
        ),
    ]
