# Generated by Django 5.1.5 on 2025-02-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profiletoken_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileToken',
        ),
    ]
