# Generated by Django 5.1.5 on 2025-01-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessarea',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='businessarea',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
