# Generated by Django 5.1.5 on 2025-02-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_alter_comment_created_by_alter_ideafolder_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_delete_%(class)s_own', 'Can delete users own %(class)s'),)},
        ),
        migrations.AlterModelOptions(
            name='ideafolder',
            options={'permissions': (('can_delete_%(class)s_own', 'Can delete users own %(class)s'),)},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'permissions': (('can_delete_%(class)s_own', 'Can delete users own %(class)s'),)},
        ),
    ]
