# Generated by Django 5.1.5 on 2025-02-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_alter_comment_options_alter_ideafolder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roundvotecount',
            options={'permissions': (('can_delete_%(class)s_own', 'Can delete users own %(class)s'),)},
        ),
        migrations.AlterModelOptions(
            name='star',
            options={'permissions': (('can_delete_%(class)s_own', 'Can delete users own %(class)s'),)},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'permissions': (('can_delete_%(class)s_own', 'Can delete users own %(class)s'),)},
        ),
    ]
