# Generated by Django 5.1.5 on 2025-02-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_alter_roundvotecount_options_alter_star_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ideafolder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roundvotecount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='star',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={},
        ),
    ]
