# Generated by Django 5.1.5 on 2025-03-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_file_created_by'),
        ('idea', '0008_alter_information_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information', to='file.file'),
        ),
    ]
