'use client';

import {ApiService} from "@/lib/api";
import {getRefreshToken, setAccessToken, setRefreshToken} from "@/lib/api/core/request";

export function login(username: string, password: string) {
    return new Promise((resolve, reject) => {
        ApiService.createTokenObtainPair({
            username,
            password
        }).then(
            (data) => {
                setAccessToken(data.access)
                setRefreshToken(data.refresh)
                resolve(data)
            },
            (error) => {
                reject(error)
            }
        )
    })
}

export function logout() {
    ApiService.createTokenBlacklist(
        {
            'refresh': getRefreshToken()
        }
    ).then(
<<<<<<< HEAD
        (data) => {
            setAccessToken(undefined)
            setRefreshToken(undefined)
=======
        () => {
            setAccessToken('')
            setRefreshToken('')
>>>>>>> feat/autogenerated-apis
        }
    )
}
